name: CSS Circle Charts
description: Simple Circle Charts using CSS
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables"]
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md"]

baseurl: ''
highlighter: pygments